# Pro Botti Configuration

# Trading Parameters
trading:
  symbols:
    - BTCUSDT
    - ETHUSDT
  timeframes:
    - 15m
    - 1h
    - 4h
  buy_threshold: 0.52
  sell_threshold: 0.48
  cooldown_seconds: 60
  enable_trading: false  # Safety: disabled by default

# Risk Management
risk:
  max_position_size_usdt: 1000
  max_drawdown_pct: 20
  stop_loss_pct: 5
  take_profit_pct: 10
  max_leverage: 1

# Data Configuration
data:
  history_path: ./data
  models_path: ./models
  history_years:
    15m: 2
    1h: 4
    4h: 10

# Model Training
training:
  features:
    - returns
    - volume
    - rsi
    - macd
    - ema_fast
    - ema_slow
  test_size: 0.2
  random_state: 42
  model_type: xgboost  # or random_forest

# Telegram Notifications
telegram:
  enabled: false
  bot_token: ""  # Set in .env
  chat_id: ""    # Set in .env

# Exchange Configuration
exchange:
  name: binance
  testnet: true
  api_key: ""     # Set in .env
  api_secret: ""  # Set in .env

# Polling & Monitoring
monitoring:
  poll_interval_seconds: 60
  health_check_enabled: true
  log_level: INFO
