max_risk_fraction: 0.01
max_leverage: 5
cooldown_bars: 1
pyramid:
  enabled: true
  max_adds: 2
  require_profit: true
atr:
  period: 14
  sl_mult_base: 1.5
  sl_mult_gain: -1.0
  tp_mult_base: 2.5
  tp_mult_gain: 1.0
circuit_breakers:
  max_daily_loss_pct: 2.0
