pairs: ["EURUSD","GBPUSD"]
timeframes: ["15m","1h"]
data_root: "data"
models_dir: "models"
target: "target"
features: ["open","high","low","close","volume"]
cv:
  n_splits: 5
  shuffle: true
  random_state: 42
