name: Deploy to server

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout (for context only)
      uses: actions/checkout@v4

    - name: Preflight — check required secrets
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_KEY:  ${{ secrets.SSH_KEY }}
      run: |
        set -euo pipefail
        missing=0
        for v in SSH_HOST SSH_USER SSH_PORT SSH_KEY; do
          if [ -z "${!v:-}" ]; then
            echo "::error:: Missing required secret: $v"
            missing=1
          fi
        done
        exit $missing

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -euo pipefail
          cd /root/pro_botti
          git fetch --all
          git checkout main
          git reset --hard origin/main
          if [ ! -x "venv/bin/python" ]; then python3 -m venv venv; fi
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          cp deploy/pro_botti.service /etc/systemd/system/ || true
          systemctl daemon-reload
          systemctl enable --now pro_botti
          if [ -f deploy/pro_botti-retrain.service ] && [ -f deploy/pro_botti-retrain.timer ]; then
            cp deploy/pro_botti-retrain.service /etc/systemd/system/ || true
            cp deploy/pro_botti-retrain.timer /etc/systemd/system/ || true
            systemctl daemon-reload
            systemctl enable --now pro_botti-retrain.timer || true
          fi
          systemctl restart pro_botti
          echo "[deploy] done"
